version: "3.9"
services:
  opa:
    image: "openpolicyagent/opa"
    ports:
      - "8181:8181"
    command: run --server
  opa-setup:
    image: "curlimages/curl"
    volumes:
      - type: bind
        source: ./example.rego
        target: /example.rego
        read_only: true
    restart: "no"
    entrypoint: ["curl","-v","-XPUT","--data-binary","@example.rego","http://opa:8181/v1/policies/example"]
    depends_on:
      - opa
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - opa-setup